### ISSUE TITLE
Rewrite and expand readme.md

### ISSUE THREAD

**Issue by shadowhen89** [Intro-to-SE-Lab-Fall-21/Group08#2]
The readme.md lacks objectives and features section. Upon closer inspection of the document, the document needs to be rewritten since the headers are off. Plus, the first header needs a new title. Might need to add links to the GitHub usernames.

**Comment by mwh273** [comment]
Henry and Matthew both changed the readme so that it satisfied the issue.

**Comment by shadowhen89** [comment]
The issue might have been closed, but this commit is still part of rewrite.
